export const BLOG_POSTS = [
  {
    id: 1,
    slug: 'best-engagement-rings-for-women',
    title: 'Best Engagement Rings for Women in 2026 — India\'s Top Styles',
    excerpt: 'Discover the most popular engagement ring styles for Indian women in 2026 — from classic diamond solitaires to romantic rose gold halos. Complete with price guide and tips.',
    date: '2026-04-20',
    dateDisplay: 'April 20, 2026',
    readTime: '7 min read',
    category: 'Engagement',
    keywords: 'best engagement rings for women india 2026, engagement ring styles, diamond engagement ring india',
    wordCount: 1200,
    image: '/diamond_cat_onhand.png'
  },
  {
    id: 2,
    slug: 'ring-size-guide-india',
    title: 'Ring Size Guide India — How to Find Your Perfect Ring Size at Home',
    excerpt: 'Measure your ring size accurately at home using our complete Indian ring size chart. Works for all finger types — no jeweller visit needed.',
    date: '2026-04-15',
    dateDisplay: 'April 15, 2026',
    readTime: '5 min read',
    category: 'Guides',
    keywords: 'ring size guide india, how to measure ring size, indian ring size chart',
    wordCount: 900,
    image: '/stylish_model.png'
  },
  {
    id: 3,
    slug: 'diamond-shapes-explained',
    title: 'Diamond Shapes Explained — Which Cut Is Right for Your Ring?',
    excerpt: 'Round, oval, princess, pear, marquise — we break down every diamond shape and help you choose the one that suits your style and budget best.',
    date: '2026-04-10',
    dateDisplay: 'April 10, 2026',
    readTime: '6 min read',
    category: 'Diamonds',
    keywords: 'diamond shapes guide, diamond cuts explained, best diamond shape engagement ring india',
    wordCount: 1100,
    image: '/diamond_cat.png'
  },
  {
    id: 4,
    slug: 'gold-vs-platinum-rings',
    title: 'Gold vs Platinum Rings — Which Metal Should You Choose?',
    excerpt: 'A complete comparison of gold and platinum rings — durability, price, appearance, and which metal works best for engagement rings in India.',
    date: '2026-04-05',
    dateDisplay: 'April 5, 2026',
    readTime: '6 min read',
    category: 'Metals',
    keywords: 'gold vs platinum ring india, platinum vs gold jewelry, which metal for engagement ring',
    wordCount: 1000,
    image: '/gold_cat_new.png'
  },
  {
    id: 5,
    slug: 'how-to-choose-a-proposal-ring',
    title: 'How to Choose a Proposal Ring — The Ultimate Guide for Indian Men',
    excerpt: 'Everything you need to know before buying a proposal ring in India — budget, style, metal, stone, and how to keep it a surprise.',
    date: '2026-03-28',
    dateDisplay: 'March 28, 2026',
    readTime: '8 min read',
    category: 'Guides',
    keywords: 'how to choose proposal ring india, engagement ring buying guide, buy proposal ring online india',
    wordCount: 1400,
    image: '/ring3.png'
  },
  {
    id: 6,
    slug: 'minimalist-jewelry-trends-2026',
    title: 'Minimalist Jewelry Trends 2026 — Less Is More in Indian Fine Jewelry',
    excerpt: 'Minimalist rings are taking India\'s jewelry market by storm in 2026. Discover the top trends, styling tips, and best minimalist rings to buy online.',
    date: '2026-03-20',
    dateDisplay: 'March 20, 2026',
    readTime: '5 min read',
    category: 'Trends',
    keywords: 'minimalist jewelry trends 2026, minimalist rings india, dainty jewelry trends india',
    wordCount: 950,
    image: '/silver_cat_new.png'
  },
  {
    id: 7,
    slug: 'best-couple-rings-online',
    title: 'Best Couple Rings Online India 2026 — His & Her Sets for Every Budget',
    excerpt: 'Discover the most beautiful couple ring sets available online in India — from affordable silver bands to luxury diamond sets. Complete buying guide with style tips.',
    date: '2026-03-12',
    dateDisplay: 'March 12, 2026',
    readTime: '7 min read',
    category: 'Couples',
    keywords: 'best couple rings online india, matching couple rings, his and her ring sets india 2026',
    wordCount: 1600,
    image: '/ring6.png'
  },
  {
    id: 8,
    slug: 'diamond-buying-guide',
    title: 'Diamond Buying Guide India — Everything You Need to Know Before You Buy',
    excerpt: 'The ultimate guide to buying a diamond ring in India. Understand the 4 Cs, certifications, pricing, and how to avoid the most common mistakes Indian buyers make.',
    date: '2026-03-05',
    dateDisplay: 'March 5, 2026',
    readTime: '9 min read',
    category: 'Buying Guide',
    keywords: 'diamond buying guide india, how to buy diamond ring india, 4cs diamond guide, IGI GIA certified diamonds',
    wordCount: 1800,
    image: '/diamond_cat_new.png'
  },
  {
    id: 9,
    slug: 'jewelry-gift-guide-for-women',
    title: 'Jewelry Gift Guide for Women — Best Ring Gifts for Every Occasion in India',
    excerpt: 'Struggling to find the perfect jewelry gift? Our curated guide covers the best ring gifts for birthdays, anniversaries, festivals, and milestones — with picks for every budget.',
    date: '2026-02-25',
    dateDisplay: 'February 25, 2026',
    readTime: '6 min read',
    category: 'Gifts',
    keywords: 'jewelry gift guide women india, best ring gift ideas, ring gifts for girlfriend wife india',
    wordCount: 1500,
    image: '/gold_cat_ornate.png'
  },
  {
    id: 10,
    slug: 'trending-rings-in-india',
    title: 'Trending Rings in India 2026 — Top Styles Dominating Indian Jewelry This Year',
    excerpt: 'From oval solitaires to mixed-metal stacks — discover the ring trends taking over India\'s jewelry market in 2026. Expert analysis with shopping recommendations.',
    date: '2026-02-15',
    dateDisplay: 'February 15, 2026',
    readTime: '6 min read',
    category: 'Trends',
    keywords: 'trending rings india 2026, ring trends india, popular ring styles india 2026',
    wordCount: 1550,
    image: '/stylish_model.png'
  },
  // --- BATCH A: DIAMOND EDUCATION (Posts 11-20) ---
  {
    id: 11,
    slug: 'diamond-clarity-guide',
    title: 'Diamond Clarity Chart Explained: VS1 vs SI1 vs VVS Jewel Guide',
    excerpt: 'Demystifying diamond clarity grades. Learn the real-world differences between VVS, VS, and SI clarity, and how to pick an eye-clean diamond ring in India.',
    date: '2026-02-08',
    dateDisplay: 'February 8, 2026',
    readTime: '8 min read',
    category: 'Diamonds',
    keywords: 'diamond clarity vs1 vs si1, diamond clarity chart, vvs clarity diamond ring india',
    wordCount: 1520,
    image: '/diamond_cat_new.png'
  },
  {
    id: 12,
    slug: 'diamond-color-guide',
    title: 'Diamond Color Grade Guide D to Z — What Matters for Indian Buyers',
    excerpt: 'Understand diamond color grades from D (colorless) to Z (yellow tint). Learn how to pick the best color grade to balance beauty and budget under Indian lighting.',
    date: '2026-02-02',
    dateDisplay: 'February 2, 2026',
    readTime: '7 min read',
    category: 'Diamonds',
    keywords: 'diamond color grade chart, d to z diamond color, best color for gold ring india',
    wordCount: 1500,
    image: '/diamond_cat_onhand.png'
  },
  {
    id: 13,
    slug: 'diamond-carat-size-guide',
    title: 'Diamond Carat Size Visual Guide — Millimeters to Carats on Finger',
    excerpt: 'How big is a 1 carat diamond ring? See visual comparisons of diamond carat sizes on hand, plus clever ways to maximize your visual ring size.',
    date: '2026-01-28',
    dateDisplay: 'January 28, 2026',
    readTime: '6 min read',
    category: 'Diamonds',
    keywords: 'diamond carat size guide, 1 carat diamond ring on hand, mm to carat weight chart',
    wordCount: 1480,
    image: '/ring1.png'
  },
  {
    id: 14,
    slug: '4cs-diamond-explained',
    title: 'The 4 Cs of Diamonds — Ultimate Indian Fine Jewelry Buying Guide',
    excerpt: 'An in-depth breakdown of Cut, Color, Clarity, and Carat. Learn which of the 4 Cs is the most critical and how to distribute your budget wisely.',
    date: '2026-01-22',
    dateDisplay: 'January 22, 2026',
    readTime: '9 min read',
    category: 'Buying Guide',
    keywords: '4cs of diamonds explained, how to buy solitaire ring india, diamond grading parameters',
    wordCount: 1720,
    image: '/diamond_cat.png'
  },
  {
    id: 15,
    slug: 'best-diamond-cuts-india',
    title: 'Best Diamond Cuts for Rings in India 2026 — Brilliance Compared',
    excerpt: 'Compare the sparkle and spread of round brilliant, princess, cushion, and oval diamond cuts. Find out which cuts are trending in India in 2026.',
    date: '2026-01-15',
    dateDisplay: 'January 15, 2026',
    readTime: '7 min read',
    category: 'Diamonds',
    keywords: 'best diamond cuts for rings, highest sparkle diamond shape, trending diamond cuts 2026',
    wordCount: 1510,
    image: '/ring2.png'
  },
  {
    id: 16,
    slug: 'igi-vs-gia-certification',
    title: 'IGI vs GIA Diamond Certification — Which is Better in India?',
    excerpt: 'Confused between IGI and GIA certificates? We break down the differences in grading consistency, market credibility, and pricing for Indian buyers.',
    date: '2026-01-08',
    dateDisplay: 'January 8, 2026',
    readTime: '8 min read',
    category: 'Buying Guide',
    keywords: 'igi vs gia certificate, certified diamonds online india, gia diamond report worth',
    wordCount: 1580,
    image: '/P1.png'
  },
  {
    id: 17,
    slug: 'lab-grown-vs-natural-diamonds',
    title: 'Lab Grown vs Natural Diamonds India — Price, Value & Purity Specs',
    excerpt: 'An unbiased comparison of lab-grown and natural diamonds. Discover the differences in chemical composition, pricing, resale value, and environmental impact.',
    date: '2025-12-28',
    dateDisplay: 'December 28, 2025',
    readTime: '8 min read',
    category: 'Diamonds',
    keywords: 'lab grown vs natural diamonds price india, eco friendly diamonds, cvd hpht diamonds',
    wordCount: 1650,
    image: '/diamond_cat_genz.png'
  },
  {
    id: 18,
    slug: 'solitaire-ring-guide',
    title: 'Solitaire Ring Complete Buying Guide — Elegant Simplicity Explained',
    excerpt: 'Thinking of buying a solitaire ring? Read our comprehensive handbook on solitaire settings, prong choices, band widths, and styling advice.',
    date: '2025-12-22',
    dateDisplay: 'December 22, 2025',
    readTime: '7 min read',
    category: 'Engagement',
    keywords: 'solitaire ring buying guide india, classic solitaire ring setting, solitaire diamond price',
    wordCount: 1530,
    image: '/ring4.png'
  },
  {
    id: 19,
    slug: 'halo-ring-guide',
    title: 'Halo Engagement Rings — Complete Style & Sparkle Guide India',
    excerpt: 'Why halo engagement rings offer the best value for your budget. Explore cushion halo, double halo, and floral designs that enhance diamond visual size.',
    date: '2025-12-15',
    dateDisplay: 'December 15, 2025',
    readTime: '6 min read',
    category: 'Engagement',
    keywords: 'halo engagement rings design, diamond halo ring price india, halo vs solitaire ring',
    wordCount: 1450,
    image: '/ring5.png'
  },
  {
    id: 20,
    slug: 'diamond-ring-care',
    title: 'How to Care for Your Diamond Ring — Keep It Sparkling Forever',
    excerpt: 'Simple home cleaning methods, professional maintenance schedules, and daily habits to protect your gold and diamond ring from damage.',
    date: '2025-12-08',
    dateDisplay: 'December 8, 2025',
    readTime: '6 min read',
    category: 'Guides',
    keywords: 'how to clean diamond ring at home, diamond ring maintenance india, jewelry care habits',
    wordCount: 1400,
    image: '/promo_jewelry_1.png'
  },
  // --- BATCH B: GOLD & METAL EDUCATION (Posts 21-30) ---
  {
    id: 21,
    slug: '22k-vs-18k-gold-rings',
    title: '22K vs 18K Gold Rings — Which Purity Should You Buy for Daily Wear?',
    excerpt: 'Compare the strength, durability, color, and investment value of 22 Karat and 18 Karat gold. Find the perfect gold alloy for your lifestyle.',
    date: '2025-12-01',
    dateDisplay: 'December 1, 2025',
    readTime: '7 min read',
    category: 'Metals',
    keywords: '22k vs 18k gold ring, best gold karat for engagement ring, 18 karat gold durability',
    wordCount: 1540,
    image: '/gold_cat.png'
  },
  {
    id: 22,
    slug: 'rose-gold-rings-india',
    title: 'Rose Gold Rings India — Style Guide & Metal Secrets Revealed',
    excerpt: 'The rise of blush metal. Learn why rose gold matches Indian skin tones perfectly, how it is alloyed, and styling tips for modern jewelry.',
    date: '2025-11-25',
    dateDisplay: 'November 25, 2025',
    readTime: '6 min read',
    category: 'Metals',
    keywords: 'rose gold rings india, 18k rose gold alloy, trendy blush pink rings',
    wordCount: 1470,
    image: '/ring7.png'
  },
  {
    id: 23,
    slug: 'bis-hallmark-explained',
    title: 'BIS Hallmark India — What It Means & Why It Matters for Rings',
    excerpt: 'A complete breakdown of government hallmarking standards in India. Learn how to read hallmark symbols and verify gold purity cards online.',
    date: '2025-11-18',
    dateDisplay: 'November 18, 2025',
    readTime: '8 min read',
    category: 'Guides',
    keywords: 'bis hallmark gold jewelry, how to verify gold hallmark online, huid number lookup',
    wordCount: 1610,
    image: '/gold_cat_new.png'
  },
  {
    id: 24,
    slug: 'white-gold-rings-india',
    title: 'White Gold Rings India — Everything You Need to Know Before Buying',
    excerpt: 'What is white gold? Learn about rhodium plating, alloy composition, re-plating schedules, and why it is the top choice for diamond rings.',
    date: '2025-11-12',
    dateDisplay: 'November 12, 2025',
    readTime: '7 min read',
    category: 'Metals',
    keywords: 'white gold rings price india, rhodium plating white gold cost, white gold vs silver',
    wordCount: 1500,
    image: '/P2.png'
  },
  {
    id: 25,
    slug: 'gold-ring-care-guide',
    title: 'Gold Ring Care Guide — Keep Your Yellow Gold Shiny and Beautiful',
    excerpt: 'Helpful tips for maintaining yellow gold jewelry. Learn about scratches, polishing techniques, and how to safely store gold rings at home.',
    date: '2025-11-05',
    dateDisplay: 'November 5, 2025',
    readTime: '5 min read',
    category: 'Guides',
    keywords: 'gold ring care guide, yellow gold polish home, safe storage fine jewelry',
    wordCount: 1380,
    image: '/gold_cat_ornate.png'
  },
  {
    id: 26,
    slug: 'platinum-ring-guide',
    title: 'Platinum Rings India — The Ultimate Buying Guide for Premium Metal',
    excerpt: 'Everything you need to know about Platinum 950. Discover its density, purity, durability, and why it is the ultimate metal for engagement bands.',
    date: '2025-10-28',
    dateDisplay: 'October 28, 2025',
    readTime: '8 min read',
    category: 'Metals',
    keywords: 'platinum rings price india, platinum 950 purity, couple platinum wedding bands',
    wordCount: 1590,
    image: '/ring8.png'
  },
  {
    id: 27,
    slug: 'gold-ring-investment-india',
    title: 'Gold Ring as Investment India — Resale Value, Making Charges & Tax',
    excerpt: 'Is buying a gold ring a good investment? Understand how making charges affect resale, how digital gold compares, and standard tax implications.',
    date: '2025-10-22',
    dateDisplay: 'October 22, 2025',
    readTime: '7 min read',
    category: 'Buying Guide',
    keywords: 'gold jewelry investment resale value, gold making charges calculation, gold purity return rate',
    wordCount: 1520,
    image: '/gold_cat.png'
  },
  {
    id: 28,
    slug: 'silver-jewelry-care',
    title: '925 Sterling Silver Jewelry Care Guide — Stop Silver Tarnishing',
    excerpt: 'Why silver tarnishes and how to prevent it. Discover easy home cleaning tips, rhodium plating benefits, and safe storage methods.',
    date: '2025-10-15',
    dateDisplay: 'October 15, 2025',
    readTime: '6 min read',
    category: 'Guides',
    keywords: 'sterling silver care guide, how to polish 925 silver at home, anti tarnish silver storage',
    wordCount: 1410,
    image: '/silver_cat_onhand.png'
  },
  {
    id: 29,
    slug: 'gemstone-rings-india',
    title: 'Natural Gemstone Rings India — Astrological Benefits & Style Trends',
    excerpt: 'From blue sapphire to emerald. Learn about setting natural gemstones in silver and gold, determining gemstone quality, and trending styles.',
    date: '2025-10-08',
    dateDisplay: 'October 8, 2025',
    readTime: '8 min read',
    category: 'Metals',
    keywords: 'natural gemstone rings online, certified birthstones rings india, emerald ring gold setting',
    wordCount: 1600,
    image: '/P3.png'
  },
  {
    id: 30,
    slug: 'ring-metals-comparison',
    title: 'Gold vs Silver vs Platinum — Ultimate Ring Metal Comparison Guide',
    excerpt: 'Struggling to pick a metal? A detailed comparison of durability, maintenance, color stability, and price points to help you choose.',
    date: '2025-10-01',
    dateDisplay: 'October 1, 2025',
    readTime: '7 min read',
    category: 'Metals',
    keywords: 'platinum vs white gold price difference, gold silver comparison, hypoallergenic ring metals',
    wordCount: 1530,
    image: '/promo_silver_1.png'
  },
  // --- BATCH C: SHOPPING & OCCASIONS (Posts 31-40) ---
  {
    id: 31,
    slug: 'online-jewelry-safety-tips',
    title: 'How to Buy Jewelry Safely Online — Expert Red Flags & Checklist',
    excerpt: 'Avoid scams and low-quality items. A comprehensive checklist on return policies, secure shipping, online certificates, and reviews verification.',
    date: '2025-09-25',
    dateDisplay: 'September 25, 2025',
    readTime: '7 min read',
    category: 'Guides',
    keywords: 'buy jewelry safely online, fine jewelry purchase safety check, online diamond seller review',
    wordCount: 1490,
    image: '/promo_jewelry_2.png'
  },
  {
    id: 32,
    slug: 'anniversary-ring-guide',
    title: 'Anniversary Ring Ideas India — Milestone Guide & Style Inspiration',
    excerpt: 'Celebrate your milestones. A complete year-by-year guide to gifting anniversary rings, eternity bands, and upgrading solitaire sizes.',
    date: '2025-09-18',
    dateDisplay: 'September 18, 2025',
    readTime: '6 min read',
    category: 'Gifts',
    keywords: 'anniversary ring ideas, eternity band anniversary gift, upgrading engagement ring solitaire',
    wordCount: 1450,
    image: '/ring3.png'
  },
  {
    id: 33,
    slug: 'valentines-ring-gift-india',
    title: 'Valentine\'s Day Ring Gifts India — Romantic Promise & Couple Sets',
    excerpt: 'Make Valentine\'s Day unforgettable. Explore romantic rings, budget-friendly couple bands, and fine jewelry gifts she will cherish.',
    date: '2025-09-11',
    dateDisplay: 'September 11, 2025',
    readTime: '6 min read',
    category: 'Gifts',
    keywords: 'valentines day ring gift, promise rings for girlfriend india, valentines couple ring sets',
    wordCount: 1420,
    image: '/promo_silver_2.png'
  },
  {
    id: 34,
    slug: 'diwali-jewelry-gift-guide',
    title: 'Diwali Jewelry Gift Guide India — Auspicious Gold & Silver Rings',
    excerpt: 'Dhanteras and Diwali shopping guide. Discover the most auspicious jewelry styles to bring prosperity and make meaningful gifts.',
    date: '2025-09-05',
    dateDisplay: 'September 5, 2025',
    readTime: '7 min read',
    category: 'Gifts',
    keywords: 'diwali gold ring purchase, dhanteras jewelry shopping guidelines, auspicious gifts family',
    wordCount: 1510,
    image: '/gold_cat_ornate.png'
  },
  {
    id: 35,
    slug: 'mother-ring-gift-india',
    title: 'Best Ring Gifts for Mothers India — Celebrate Mom with Fine Jewelry',
    excerpt: 'Find the perfect ring for mothers. Explore traditional gold bands, elegant minimalist stackers, and birthstone rings with deep meaning.',
    date: '2025-08-28',
    dateDisplay: 'August 28, 2025',
    readTime: '6 min read',
    category: 'Gifts',
    keywords: 'ring gifts for mothers, jewelry gift for mom india, fine rings mother birthday',
    wordCount: 1430,
    image: '/P4.png'
  },
  {
    id: 36,
    slug: 'bridal-ring-checklist',
    title: 'Indian Bride\'s Complete Ring Checklist — Engagement to Wedding Day',
    excerpt: 'A step-by-step ring planner for brides. Coordination of engagement, wedding, and reception rings with your bridal lehenga and outfits.',
    date: '2025-08-20',
    dateDisplay: 'August 20, 2025',
    readTime: '7 min read',
    category: 'Engagement',
    keywords: 'bridal ring checklist india, coordinate bridal jewelry with lehenga, wedding ring ensemble bride',
    wordCount: 1560,
    image: '/stylish_model.png'
  },
  {
    id: 37,
    slug: 'wedding-ring-etiquette-india',
    title: 'Wedding Ring Traditions & Etiquette India — Left Hand vs Right Hand',
    excerpt: 'Which finger does the engagement ring go on in India? Explore history, cultural differences, and modern practices of wearing wedding rings.',
    date: '2025-08-12',
    dateDisplay: 'August 12, 2025',
    readTime: '6 min read',
    category: 'Guides',
    keywords: 'which hand for wedding ring india, engagement ring finger tradition, indian wedding ring rules',
    wordCount: 1440,
    image: '/P5.png'
  },
  {
    id: 38,
    slug: 'how-to-surprise-proposal-india',
    title: 'How to Plan a Ring Surprise Proposal India — Sizing, Timing & Venues',
    excerpt: 'Planning a surprise proposal? Learn how to measure her ring size secretly, pick a perfect romantic setting in India, and capture the moment.',
    date: '2025-08-05',
    dateDisplay: 'August 5, 2025',
    readTime: '7 min read',
    category: 'Guides',
    keywords: 'how to surprise proposal ring india, secret ring size measurement, romantic proposal ideas india',
    wordCount: 1520,
    image: '/P6.png'
  },
  {
    id: 39,
    slug: 'ring-stack-guide-india',
    title: 'How to Stack Rings India — Complete Fine Jewelry Styling Guide',
    excerpt: 'Master the art of stacking. Learn to mix gold and silver metals, arrange thin and chunky bands, and create a cohesive daily hand look.',
    date: '2025-07-28',
    dateDisplay: 'July 28, 2025',
    readTime: '6 min read',
    category: 'Trends',
    keywords: 'how to stack rings gold silver, stackable ring trends india, mix metal rings styling tips',
    wordCount: 1460,
    image: '/silver_cat.png'
  },
  {
    id: 40,
    slug: 'first-anniversary-ring',
    title: 'First Anniversary Ring Ideas India — Traditional & Modern Style Gifts',
    excerpt: 'Make your first milestone special. Compare diamond promise rings, matching couple bands, and romantic gold eternity stackers.',
    date: '2025-07-20',
    dateDisplay: 'July 20, 2025',
    readTime: '6 min read',
    category: 'Gifts',
    keywords: 'first anniversary ring gift ideas, gold ring gift for wife, first year anniversary couple bands',
    wordCount: 1400,
    image: '/ring6.png'
  },
  // --- BATCH D: TRENDS & STYLE (Posts 41-52) ---
  {
    id: 41,
    slug: 'oval-diamond-rings-india',
    title: 'Oval Diamond Rings India — The 2026 Ultimate Bridal Trend Guide',
    excerpt: 'Why oval cut diamonds are dominating bridal trends. Explore elongating settings, matching wedding bands, and custom solitaire pricing.',
    date: '2025-07-12',
    dateDisplay: 'July 12, 2025',
    readTime: '6 min read',
    category: 'Trends',
    keywords: 'oval diamond rings price india, oval solitaire engagement rings, celebrity oval cut rings',
    wordCount: 1480,
    image: '/diamond_cat_onhand.png'
  },
  {
    id: 42,
    slug: 'emerald-cut-rings-india',
    title: 'Emerald Cut Diamond Rings India — Art Deco Elegance Reimagined',
    excerpt: 'The step-cut allure. Learn why emerald-cut rings offer vintage sophistication, how to inspect clarity, and best setting designs.',
    date: '2025-07-05',
    dateDisplay: 'July 5, 2025',
    readTime: '7 min read',
    category: 'Trends',
    keywords: 'emerald cut diamond ring cost india, step cut diamond clarity guide, vintage art deco rings',
    wordCount: 1500,
    image: '/P7.png'
  },
  {
    id: 43,
    slug: 'pear-diamond-rings',
    title: 'Pear Shape Diamond Rings India — Teardrop Style & Settings Guide',
    excerpt: 'The teardrop aesthetic. How to wear pear shape diamonds, choose orientations (tip up or tip down), and find the best halo settings.',
    date: '2025-06-28',
    dateDisplay: 'June 28, 2025',
    readTime: '6 min read',
    category: 'Trends',
    keywords: 'pear shape diamond ring india, teardrop diamond rings gold, pear solitaire styling',
    wordCount: 1410,
    image: '/P8.png'
  },
  {
    id: 44,
    slug: 'cushion-cut-rings-india',
    title: 'Cushion Cut Diamond Rings India — Vintage Pillow Cut Buying Guide',
    excerpt: 'Discover cushion cut pillow diamonds. Compare old mine cuts with modern cushion modifications, plus best yellow gold halo settings.',
    date: '2025-06-20',
    dateDisplay: 'June 20, 2025',
    readTime: '6 min read',
    category: 'Trends',
    keywords: 'cushion cut diamond ring india, pillow cut solitaire settings, antique cushion diamonds',
    wordCount: 1420,
    image: '/P9.png'
  },
  {
    id: 45,
    slug: 'princess-cut-rings-india',
    title: 'Princess Cut Diamond Ring India — Square Solitaire Trend Guide',
    excerpt: 'Clean, geometric brilliance. Why the princess cut is a timeless modern favorite, corner protection tips, and affordable settings.',
    date: '2025-06-12',
    dateDisplay: 'June 12, 2025',
    readTime: '7 min read',
    category: 'Trends',
    keywords: 'princess cut diamond ring price, square diamond rings gold, princess solitaire settings',
    wordCount: 1530,
    image: '/ring2.png'
  },
  {
    id: 46,
    slug: 'boho-rings-india',
    title: 'Bohemian Ring Styles India 2026 — Organic Textures & Raw Stones',
    excerpt: 'The free-spirited hand. Discover organic jewelry textures, crescent moon motifs, and stacking raw cut gemstone silver bands.',
    date: '2025-06-05',
    dateDisplay: 'June 5, 2025',
    readTime: '6 min read',
    category: 'Trends',
    keywords: 'boho rings sterling silver india, hammered metal rings boho, organic gemstone stackers',
    wordCount: 1390,
    image: '/silver_cat_new.png'
  },
  {
    id: 47,
    slug: 'statement-rings-india',
    title: 'Statement Rings India — Bold Custom Jewelry Styles for 2026',
    excerpt: 'Make your presence felt. Learn to style oversized cocktail rings, ornate gold shields, and multi-finger diamond bands.',
    date: '2025-05-28',
    dateDisplay: 'May 28, 2025',
    readTime: '7 min read',
    category: 'Trends',
    keywords: 'statement rings online india, gold cocktail rings luxury, bold designer diamond bands',
    wordCount: 1510,
    image: '/gold_cat_ornate.png'
  },
  {
    id: 48,
    slug: 'daily-wear-rings-india',
    title: 'Best Daily Wear Rings India — Lightweight Durable Gold & Silver',
    excerpt: 'Jewelry for everyday. Find comfortable, scratch-resistant daily wear rings in hallmarked 18k gold and 925 sterling silver.',
    date: '2025-05-20',
    dateDisplay: 'May 20, 2025',
    readTime: '6 min read',
    category: 'Guides',
    keywords: 'best daily wear gold rings, lightweight silver rings india, durable rings home cleaning',
    wordCount: 1430,
    image: '/silver_cat_onhand.png'
  },
  {
    id: 49,
    slug: 'vintage-rings-india',
    title: 'Vintage Inspired Rings India 2026 — Art Deco & Victorian Revival',
    excerpt: 'The charm of history. Learn about milgrain borders, filigree detailing, antique diamond cuts, and choosing vintage style bands.',
    date: '2025-05-12',
    dateDisplay: 'May 12, 2025',
    readTime: '7 min read',
    category: 'Trends',
    keywords: 'vintage inspired engagement rings india, art deco ring settings gold, milgrain filigree bands',
    wordCount: 1500,
    image: '/stylish_model.png'
  },
  {
    id: 50,
    slug: 'luxury-jewelry-brands-india',
    title: 'Top Luxury Jewelry Brands India 2026 — Fine Rings Market Analysis',
    excerpt: 'An industry overview of premium Indian jewelry brands. Discover trends, online customizations, certifications, and market insights.',
    date: '2025-05-05',
    dateDisplay: 'May 5, 2025',
    readTime: '7 min read',
    category: 'Buying Guide',
    keywords: 'top luxury jewelry brands india, premium fine rings manufacturer, certified diamond brand market',
    wordCount: 1540,
    image: '/ring8.png'
  },
  {
    id: 51,
    slug: 'buying-gold-coins-vs-jewelry',
    title: 'Gold Coins vs Gold Jewelry India — Best Wealth Investment Compared',
    excerpt: 'Comparing wealth assets. Learn about gold coin purity, hallmark jewelry making charges, resale value, and tax rules on physical gold.',
    date: '2025-04-28',
    dateDisplay: 'April 28, 2025',
    readTime: '7 min read',
    category: 'Buying Guide',
    keywords: 'gold coin vs gold jewelry investment, gold making charges loss, wealth tax physical gold',
    wordCount: 1550,
    image: '/gold_cat.png'
  },
  {
    id: 52,
    slug: 'mens-engagement-rings-india',
    title: 'Men\'s Engagement Rings India — Trending Gold, Silver & Platinum Bands',
    excerpt: 'The rise of grooms rings. Explore trending matte bands, flush set diamonds, classic yellow gold, and durable platinum designs for men.',
    date: '2025-04-20',
    dateDisplay: 'April 20, 2025',
    readTime: '6 min read',
    category: 'Engagement',
    keywords: 'mens engagement rings gold india, groom wedding band platinum, masculine ring designs',
    wordCount: 1470,
    image: '/ring6.png'
  }
];
